flowchart LR
    A[Work Package 5<br>Indicator Workflow<br>Catalogue & Dashboard]:::wp

    subgraph Activities
        A1[Requirements Gathering<br>with stakeholders & end users]:::act
        A2["Design & Operationalise<br>Catalogue (MVP)"]:::act
        A3[Dashboard App for<br>Indicator Development Tracking]:::act
    end
    A1b["Identify functionality for<br>key user groups<br>Identify requirements for:<br>Metadata structure<br>Integration points<br>User interface"]:::act
    A2a["Catalogue design"]:::act
    A2b[Build & deploy MVP]:::act
    A3a[Design dashboard metrics,<br> hierarchy views,<br>status/coverage indicators]:::act
    A3b[Build & deploy MVP]:::act

    subgraph Deliverables
        D1["High-level requirements &<br>constraints documented"]:::del
        D2["User requirements<br>for catalogue outlined"]:::del
        D3["Catalogue design<br>documented"]:::del
        D4["Workflow catalogue<br>MVP operational"]:::del
        D5["User requirements<br>for dashboard outlined"]:::del
        D6["Dashboard MVP<br>operational"]:::del
    end

    %% Activity structure
    A --> A1 --> A1b
    

    A --> A2 --> A2a
    A2 --> A2b

    A --> A3 --> A3a
    A3 --> A3b

    %% Activities to Deliverables mapping
    A1 --> D1
    A1b --> D2

    A2a --> D3
    A2b --> D4

    A3a --> D5
    A3b --> D6

    %% Styles
    Activities:::Empty
    Deliverables:::Empty
    classDef Empty fill:none,stroke:black;
    classDef wp fill:#0b6efd,color:#fff,stroke:#084298,stroke-width:2px;
    classDef act fill:#e7f1ff,color:#052c65,stroke:#9ec5fe,stroke-width:1px;
    classDef del fill:#e8f5e9,color:#1b5e20,stroke:#a5d6a7,stroke-width:1px;